import type { Metadata } from "next";
import "./globals.css";
import localFont from '@next/font/local'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const monasans = localFont({
  src: [
    {
      path: './fonts/MonaSans/OTF/MonaSans-Regular.otf',
      weight: '400'
    },
  ],
  variable: '--font-monasans'
})

const nohemiBold = localFont({
  src: [
    {
      path: './fonts/Nohemi_Font/Nohemi-Bold-BF6438cc577b524.woff',
    },
  ],
  variable: '--font-nohemiBold'
})

// Nohemi-Bold-BF6438cc577b524.woff

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${monasans.variable} ${nohemiBold.variable} antialiased bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
